Repository forkyid/go-utils, pull requests merged in 2020-09, with the labels that each got.

#13 Add Redis
  redis/.gitignore
  redis/cache.go
  redis/connect.go
  redis/go.mod
Labels: enhancement

#14 refactor: http request function
  rest/rest.go
Labels: enhancement

#15 fix redis package name
  cache/.gitignore
  cache/cache.go
  cache/connect.go
  cache/go.mod
Labels: bug

#16 refactor redis utils
  cache/cache.go
  cache/connect.go
  cache/go.mod
Labels: bug, enhancement

#17 Bug MethodGet & Logger User Activity
  logger/go.mod
  logger/logger.go
  rest/rest.go
Labels: bug, enhancement

#18 Fix Import Cycle
  logger/go.mod
  logger/logger.go
Labels: bug, enhancement
