Repository forkyid/go-utils, pull requests merged in 2020-11, with the labels that each got.

#28 Added pagination for go-utils
  pagination/.gitignore
  pagination/aes.go
  pagination/go.mod
Labels: enhancement

#29 fix: update aes
  rest/go.mod
Labels: bug

#30 request with context headers + middleware
  middleware/.gitignore
  middleware/auth.go
  middleware/cors.go
  middleware/go.mod
  rest/request.go
  rest/rest.go
Labels: enhancement

#31 fix: auth middleware
  cache/key.go
  middleware/auth.go
Labels: bug, enhancement

#32 adjustments to go mod and logger + ES + minor refactors + new redis function
  .gitignore
  aes/go.mod
  cache/.gitignore
  cache/cache.go
  cache/go.mod
  cache/key.go
  elasticsearch/elasticsearch.go
  go.mod
  jwt/.gitignore
  jwt/go.mod
  logger/.gitignore
  logger/go.mod
  logger/logger.go
  middleware/.gitignore
  middleware/go.mod
  pagination/.gitignore
  pagination/go.mod
  pagination/pagination.go
  rest/.gitignore
  rest/go.mod
  rest/pagination/pagination.go
  rest/request.go
  rest/rest.go
  uuid/.gitignore
  uuid/go.mod
Labels: bug, enhancement
