Repository forkyid/go-utils, pull requests merged in 2020-12, with the labels that each got.

#33 refactor cache and allow location headers
  cache/cache.go
  middleware/cors.go
Labels: enhancement

#34 Clean Up Validator V10 Update
  go.mod
  validation/.gitignore
  validation/go.mod
  validation/validation.go
Labels: bug, enhancement

#35 refactor login
  elasticsearch/elasticsearch.go
  middleware/auth.go
  middleware/cors.go
  middleware/interface.go
  rest/request.go
Labels: enhancement

#36 [go-utils/pagination] Granularized pagination functionality & add total page
  pagination/pagination.go
  pagination/type.go
Labels: documentation, enhancement

#39 feat: integration API Activity
  rest/entity.go
  rest/rest.go
Labels: enhancement

#38 [go-utils/pagination] Add unit testing and benchmark for pagination package
  go.mod
  pagination/pagination.go
  pagination/pagination_test.go
Labels: enhancement, unit testing
