Repository forkyid/go-utils, pull requests merged in 2021-08, with the labels that each got.

#59 [AI-60] Debug go-utils Publisher for AI
  v1/rabbitmq/publisher/v1/exchange.go
  v1/rest/rest.go
Labels: bug, enhancement

#60 [COREAPI-352] ResponsePagination, body -> result on response
  v1/rest/rest.go
Labels: enhancement, help wanted

#61 [COREAPI-355] request bind helper
  v1/rest/bind.go
  v1/rest/rest.go
Labels: enhancement, help wanted

#62 [COREAPI-396] remove restid-related helper, jwt generator, refactor logger
  go.mod
  v1/jwt/entity.go
  v1/jwt/generate.go
  v1/logger/logger.go
  v1/middleware/auth.go
  v1/rest/readme.md
  v1/rest/restid/restid.go
  v1/validation/validation.go
Labels: bug, enhancement, help wanted

#64 refactor: remove whitelist checking to elastic
  v1/middleware/auth.go
Labels: enhancement
