Repository forkyid/go-utils, pull requests merged in 2021-09, with the labels that each got.

#65 [AI-110] Check RabbitMQ Error When Publishing in API
  v1/rabbitmq/connect.go
  v1/rabbitmq/publisher/v1/exchange.go
Labels: bug

#66 Disable publish log
  v1/rest/rest.go
Labels: help wanted, dependencies

#67 [AI-204] NSQ Publisher
  go.mod
  v1/nsq/connect.go
  v1/nsq/publisher/v1/producer.go
  v1/rabbitmq/publisher/v1/handler.go
  v1/rest/rest.go
Labels: enhancement

#68 [COREAPI-782] Update auth middleware check access token expiry
  go.mod
  v1/jwt/entity.go
  v1/jwt/extract.go
  v1/middleware/auth.go
Labels: enhancement
